image: alpine:latest

pages:
  stage: deploy
  script:
  - ssh $SSH_USER@$VM_IPADDRESS "hostname && echo 'Welcome!!!' > welcome.txt"
  artifacts:
    paths:
    - /home/www/the-io/shadows
  only:
  - master